services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command:
      ["make", "dev"]
  caddy:
    image: caddy
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
